spring.application.name=Semana6
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jpa.open-in-view=false

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Datasource H2 en memoria con nombre fijo
spring.datasource.url=jdbc:h2:mem:videojuegosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate: crea la tabla a partir de la @Entity
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
